### ISSUE TITLE
1.1.7 Does it not work with https?

### ISSUE THREAD

**Issue by coolAlias** [Dynious/VersionChecker#60]
Hi,

I've been trying for a while to use Version Checker for one of my mods, but with no success.

File hosted on Github: https://github.com/coolAlias/DynamicSwordSkills/blob/1.7.10/src/main/resources/versionlist.json

IMC sent during FMLInitializationEvent:
String link = "https://github.com/coolAlias/DynamicSwordSkills/blob/1.7.10/src/main/resources/versionlist.json";
FMLInterModComms.sendRuntimeMessage(ModInfo.ID, "VersionChecker", "addVersionCheck", link);

I don't see any messages in the log that my IMC was received and, if so, whether it can or cannot access that file.

I don't see any change in the main menu screen, either, even after making a build of my mod with a lower version than in the online file.

It would be helpful, I think, to always show the button and allow viewing of mods which are using Version Checker, with an error notice for those that are not working properly.

Anyway, is it possible to host the file on Github like that, or will I need to figure something else out?

**Comment by squeek502** [comment]
You need to send the link to the *raw* file, like so:
https://raw.githubusercontent.com/coolAlias/DynamicSwordSkills/1.7.10/src/main/resources/versionlist.json

**Comment by coolAlias** [comment]
Aha, that did the trick! Awesome xD
