### ISSUE TITLE
Thaumic Tinkerer Version Unspecified and Says Needs Update when Newest Version

### ISSUE THREAD

**Issue by duhadventure** [Dynious/VersionChecker#64]
Whenever I update Thaumic Tinkerer it says the version I have is unspecified and that it needs to be updated when I have the latest version.
![image](https://cloud.githubusercontent.com/assets/8278338/6997332/5bb713b8-db7d-11e4-824b-0ff46d955f26.png)

![image](https://cloud.githubusercontent.com/assets/8278338/6997328/4793a158-db7d-11e4-8d2d-d3408bb2fabd.png)

**Comment by Dynious** [comment]
This is handled by Thaumic Tinkerer (they didn't set the version in-file), I don't think there's a lot I can do.
