### ISSUE TITLE
Chisels & Bits 1.2 -> 1.2

### ISSUE THREAD

**Issue by AlgorithmX2** [Dynious/VersionChecker#65]
![Screenshot](https://dl.dropboxusercontent.com/u/9117298/vc_curse.png)

I used the curse version checker IMC and for some reason its suggesting updating even tho the versions are the same, is this a bug, or did I forget something?

**Comment by Dynious** [comment]
Thanks for reporting! You didn't forget something, I did :P 
When #67 is updated, I'll merge both fixes into the 1.8 branch and release a new version!

**Comment by AlgorithmX2** [comment]
Sounds good to me :+1:
