### ISSUE TITLE
Update version bug

### ISSUE THREAD

**Issue by Keridos** [Dynious/VersionChecker#70]
I have a mod here and Version Checker tells me I can upgrade from "2.0.0-0" to "1.3.8-35" which is clearly an older version. Can you maybe fix detection for versionnumber-buildnumber schemes?
Note: Using 1.1.9 on 1.7.10 here. Note, this is when using non released builds.

**Comment by Dynious** [comment]
"Note, this is when using non released builds." This is probably not a NEM update (see the icon), which means the update is not checked by Version Checker, but just displayed because the mod said it had a version that wasn't the latest. Nothing I can do :(

**Comment by Keridos** [comment]
Hm, so you cannot change that one being set. Couldn't you override the version check and hide it if the version mismatch?

**Comment by Dynious** [comment]
I could, there has been a suggestion to add a blacklist function for users, but I haven't had the time to think of a good way to implement the while keeping it easy, and clear, to use.

**Comment by Keridos** [comment]
That update seems to just ignore the version comparing algorithm you use when checking updates from NEM apparently.

**Comment by Keridos** [comment]
This is a curse update check btw.
