### ISSUE TITLE
Two mods saying they need updates when they are the newest version

### ISSUE THREAD

**Issue by osum4est** [Dynious/VersionChecker#74]
Hello! Awesome mod. Two mods that I'm using, though, say they need an update, but they are the latest version.

Micdoodle8 Core says " -> 3.0.11.333". I've triple checked, and i'm using that version.
Modular Forcefield System says "3.0-ALPHA-7 -> 3.0-Alpha-7". Seems like the all caps is causing a problem.

A fix for these would be greatly appreciated!

**Comment by KIdWither** [comment]
I also seem to be having a similar issue with the thamic tinker 164 build released on curse, asking for me to install build 164 when that is what I have .

**Comment by Dynious** [comment]
Thanks for reporting. I'm not sure if I'll be able to fix these issues. Mods sometimes don't set their ingame version correctly resulting in these false positives.

**Comment by osum4est** [comment]
I'm pretty sure its the mod authors fault. Their .info file is messes up. I changed the all caps the regular case for mffs and that fixed it. Micdoodle, though, doesn't even have that file!

**Comment by KIdWither** [comment]
I'm not blaming anyone but, it is annoying (it is tolerable).

**Comment by Geforce132** [comment]
I'll try to help minimize the issue by hiding any update that's the same version as the version you have installed.
