### ISSUE TITLE
[Bug] 1.7.10 Shows Newer Mods Needing to Update to Older Versions

### ISSUE THREAD

**Issue by chrisay** [Dynious/VersionChecker#80]
Multiple mods are shown as needing to "update" from a more current version to an older version.
Suspecting this may be on the mod authors' end though.

http://pasteboard.co/1hwA2ofP.png

**Comment by ThexXTURBOXx** [comment]
This is, because the mod only checks, if the old version is the same text string as the new version. if it is not equal, then the mod is outdated. I know, that Iguana Tinker Tweaks needs to get an updated version-file, like many other mods. Ask their mod authors. It is not a bug of this mod.

**Comment by chrisay** [comment]
I appreciate the follow-up and clarification. That's what I had been suspecting as I gave the issue some more thought. Marking this as closed.
